
version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: material_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
