# Railway configuration for backend deployment
[build]
buildCommand = "pip install -r backend/requirements.txt"

[deploy]
startCommand = "python backend/main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
ENV = "production"
PORT = "8000"